// Categories constants
export const REQUEST_CATEGORY = 'REQUEST_CATEGORY';
export const REQUEST_CATEGORIES = 'REQUEST_CATEGORIES';
export const RECEIVE_CATEGORY = 'RECEIVE_CATEGORY';
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const SET_CATEGORIES_ERRORS = 'SET_CATEGORIES_ERRORS';